########################
#Part 1: Mount the disk#
########################
#Note: Replace <NFS server host> with the NFS server host name
#Note: Replace <mount point at NFS server>, example: /media/nfs
- hosts: <NFS server host>
  gather_facts: no
  become: true
  user: user
  tasks:
  - name: Creates directory for mount point*
    file:
      path: "{{ item }}"
      state: directory
      owner: nobody
      group: nobody
      mode: 0777
    loop:
     - <mount point at NFS server>

#Note: Replace <label> with the disk/storage label
  - name: Get UUID of disk using label 
    shell:
      blkid | grep <label> | awk -F"UUID=" '{print $2}' | awk -F"\"" '{print $2}'
    register: storage_uuid_cmdout
  - name: Set fact/variable for <label> storage dev
    set_fact: 
      storage_uuid: "{{ storage_uuid_cmdout.stdout }}"
  - debug:
      msg: "{{ storage_uuid }}"


#Mount units must be named after the mount point directories they control. 
#Example: the mount point of /home/regularuser/diskmount must be configured in a unit file as home-regularuser-diskmount.mount.
#Replace all "mount-point-at-NFS-server" with the correct name

  - name: Create mount-point-at-NFS-server.mount to automount disk using systemd
    copy:
      dest: "/etc/systemd/system/mount-point-at-NFS-server.mount"
      content: |
        [Unit]
        Description=Auto mount disks with systemd

        [Mount]
        What=/dev/disk/by-uuid/{{ storage_uuid }}
        Where=<mount point at NFS server>
        Type=ntfs
        Options=defaults

        [Install]
        WantedBy=multi-user.target

#########################
#Part 2: NFS server setup
#########################
  - name: Install apt nfs server package on Fedora distro
    dnf:
      name: nfs-utils
      state: present

#Update /etc/exports for NFS connection
#Note: Replace <mount point at NFS server>, example: /media/nfs
  - name: Update /etc/exports for NFS connection
    lineinfile:
      path: /etc/exports
      state: present
      line: "{{ item }}"
    with_items:
    - "<mount point at NFS server> *(rw,sync,no_subtree_check)"
#The star allow the NFS server to accept request from any IP.


#Reload
  - name: Reload systemd
    systemd:
      daemon_reload: yes

#Start systemd mount
  - name: Enable mount-point-at-NFS-server.mount
    systemd:
      name: mount-point-at-NFS-server.mount
      enabled: yes
      masked: no
  - name: Restart mount-point-at-NFS-server.mount
    systemd:
      name: mount-point-at-NFS-server.mount
      state: restarted

  - name: Enable media-homeshare-WD4TB.mount
    systemd:
      name: media-homeshare-WD4TB.mount
      enabled: yes
      masked: no
  - name: Restart media-homeshare-WD4TB.mount
    systemd:
      name: media-homeshare-WD4TB.mount
      state: restarted

#Start NFS server
  - name: Enable rpcbind
    systemd:
      name: rpcbind
      enabled: yes
      masked: no
  - name: Enable nfs-server
    systemd:
      name: nfs-server
      enabled: yes
      masked: no
  - name: Restart systemd rpcbind
    systemd:
      name: rpcbind
      state: restarted
  - name: Restart systemd nfs-server
    systemd:
      name: nfs-server
      state: restarted
